manifest:
  remotes:
    - name: stephen/split-encoder
      url-base: https://github.com/stephen/zmk
  projects:
    - name: stephen/split-encoder
      remote: zmkfirmware
      revision: stephen/split-encoder
      import: app/west.yml
  self:
    path: config
