manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/NikolaRavic
  projects:
    - name: zmk-firmware
      remote: zmkfirmware
      revision: encoders-peripheral
      import: app/west.yml
  self:
    path: config
